import type { Metadata } from 'next'
import ThemeRegistry from "@/app/ThemeRegistry";
import { Inter } from 'next/font/google'
import './globals.css'

// Roboto Font (default for MUI)
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import { Navbar } from './components/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeRegistry options={{ key: 'mui' }}>
        <Navbar />
        {children}
      </ThemeRegistry>
      </body>
    </html>
  )
}
